import Singmaster
open Singmaster
#print axioms card_le_singmasterCount
#print axioms eight_le_singmasterCount_3003
#print axioms eight_le_of_singmasterConjecture
#print axioms four_le_of_singmasterConjecture
#print axioms singmasterCount_six
#print axioms two_le_singmasterCount
